[project]
name = "bootstrap-inference"
version = "1.0.0"
description = "Extensible bootstrap inference in Python."
readme = "README.md"
authors = [
    { name = "Enej Hudobreznik", email = "hudobreznik.enej.04@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.3",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Documentation = "https://bootstrap-inference.readthedocs.io"
Source = "https://github.com/enejH04/bootstrap-inference"
Issues = "https://github.com/enejH04/bootstrap-inference/issues"

[build-system]
requires = ["uv_build>=0.11.25,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.15.7",
    "sphinx>=9.1.0",
    "sphinx-rtd-theme>=3.1.0",
]
lme-experiments = [
    "rpy2>=3.6.7",
    "ipykernel>=7.2.0",
    "scipy>=1.18.0",
]
performance-validation = [
    "bootstrap-ci>=0.0.1",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numba>=0.66.0",
    "scipy>=1.18.0",
]

[tool.ruff]
line-length = 80
exclude = [".venv"]

[tool.ruff.lint]
select = [
    "I",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
