[project]
name = "bootstrap-diagnostics"
version = "0.1.0"
description = "Double bootstrap with diagnostic tests"
readme = "README.md"
authors = [
    { name = "enejH04", email = "hudobreznik.enej.04@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.3",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
]

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.15.7",
]
performance-validation = [
    "bootstrap-ci>=0.0.1",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numba>=0.66.0",
]

[tool.ruff]
line-length = 80
exclude = [".venv"]

[tool.ruff.lint]
select = [
    "I",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
