from pathlib import Path

import numpy as np
import pandas as pd

if __name__ == "__main__":
    # See whether the bounds generated by the comparison on different platforms
    # match
    folder = Path(__file__).resolve().parent

    csv_linux = pd.read_csv(folder / "pilot_results_linux/results.csv")
    csv_mac = pd.read_csv(folder / "pilot_results_mac/results.csv")

    bounds_linux = csv_linux[["ci_lower", "ci_upper"]].to_numpy()
    bounds_mac = csv_mac[["ci_lower", "ci_upper"]].to_numpy()

    if not np.allclose(bounds_linux, bounds_mac, atol=1e-10):
        print("The bounds don't match across platforms! Reproducibility issue!")
    else:
        print("The bounds match across platforms! Success.")
