from pathlib import Path

import numpy as np
import pandas as pd

if __name__ == "__main__":
    # See whether the bounds generated by the comparison on different platforms match
    folder = Path(__file__).resolve().parent

    linux = pd.read_csv(folder / "pilot_results_linux/results.csv")
    mac = pd.read_csv(folder / "pilot_results_mac/results.csv")

    # Keys by which the pairing is done (so we compare corresponding cases)
    pair_keys = [
        "dgp",
        "statistic",
        "n",
        "B",
        "method",
        "replication_id",
        "library",
        "bootstrap_seed",
    ]

    linux = linux.sort_values(pair_keys).reset_index(drop=True)
    mac = mac.sort_values(pair_keys).reset_index(drop=True)

    # Ensure bounds belong to identical experiments and replications.
    # This isn't really needed but just in case
    pd.testing.assert_frame_equal(
        linux[pair_keys],
        mac[pair_keys],
        check_dtype=False,
    )

    for column in ["ci_lower", "ci_upper"]:
        linux_values = linux[column].to_numpy()
        mac_values = mac[column].to_numpy()

        # Ensure construction failures occur in identical places.
        np.testing.assert_array_equal(
            np.isnan(linux_values),
            np.isnan(mac_values),
        )

        # Assert bounds are the same, with absolute tolerance 1e-10
        np.testing.assert_allclose(
            linux_values,
            mac_values,
            rtol=0,
            atol=1e-10,
            equal_nan=True,
        )

    print("The bounds match across platforms.")
